project:
  machine_name: greenmachine
  prefix: GREEN
  human_name: 'Green Machine'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}.com'
git:
  default_branch: master
  remotes: {  }
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: {  }
    uninstall: {  }
  test:
    enable: {  }
    uninstall: [devel, views_ui]
  prod:
    enable: {  }
    uninstall: [devel, views_ui]
